//EXPERIENCE ACTIONS

export const FETCHING_EXPERIENCES = "FETCHING_EXPERIENCES"
export const FETCH_EXPERIENCES = "FETCH_EXPERIENCES"

export const CREATING_EXPERIENCE = "CREATING_EXPERIENCE"
export const CREATE_EXPERIENCE = "CREATE_EXPERIENCE"
export const CREATE_EXPERIENCE_ERROR = "CREATE_EXPERIENCE_ERROR"

export const SAVED_EXPERIENCE = "SAVED_EXPERIENCE"
export const SAVED_EXPERIENCE_ERROR = "SAVED_EXPERIENCE_ERROR"

export const UNSAVED_EXPERIENCE = "UNSAVED_EXPERIENCE"
export const UNSAVED_EXPERIENCE_ERROR = "UNSAVED_EXPERIENCE_ERROR"


export const LIKE_EXPERIENCE = "LIKE_EXPERIENCE"
export const LIKE_EXPERIENCE_FAILED = "LIKE_EXPERIENCE_FAILD"

export const DISLIKE_EXPERIENCE = "DISLIKE_EXPERIENCE"
export const DISLIKE_EXPERIENCE_FAILED = "DISLIKE_EXPERIENCE_FAILD"

export const DELETING_EXPERIENCE = "DELETING_EXPERIENCE"
export const DELETE_EXPERIENCE = "DELETE_EXPERIENCE"
export const DELETE_EXPERIENCE_FAILED = 'DELETE_EXPERIENCE_FAILED'

export const COMMENT_EXPERIENCE = "COMMENT_EXPERIENCE"
export const COMMENT_EXPERIENCE_ERROR = "COMMENT_EXPERIENCE_ERROR"

export const LIKE_COMMENT = "LIKE_COMMENT"
export const LIKE_COMMENT_FAILED = "LIKE_COMMENT_FAILED"

export const UNLIKE_COMMENT = "UNLIKE_COMMENT"
export const UNLIKE_COMMENT_FAILED = "UNLIKE_COMMENT_FAILED"


export const DELETE_COMMENT = "DELETE_COMMENT"
export const DELETE_COMMENT_FAILED = "DELETE_COMMENT_FAILED"



// AUTHENTICATION ACTIONS

export const SIGNING_UP = "SIGNING_UP"
export const SIGNED_UP = "SIGNED_UP"
export const SIGN_UP_ERROR = "SIGN_UP_ERROR"

export const SIGNING_IN = "SIGNING_IN"
export const SIGNED_IN = "SIGNED_IN"
export const SIGN_IN_ERROR = "SIGN_IN_ERROR"


export const FETCHING_ACCOUNT = "FETCHING_ACCOUNT"
export const FETCHED_ACCOUNT = "FETCHED_ACCOUNT"
export const FETCHED_ACCOUNT_FAILED = "FETCHED_ACCOUNT_FAILED"

export const UPDATING_ACCOUNT = "UPDATING_ACCOUNT"
export const UPDATED_ACCOUNT = "UPDATED_ACCOUNT"
export const UPDATE_ACCOUNT_FAIL = "UPDATE_ACCOUNT_FAIL"

export const LOGGED_OUT = "LOGGED_OUT"



// ERRORS ACTIONS
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR"
export const CLEAR_ERRORS = "CLEAR_ERRORS"